version: "3.7"
services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: mcsimpy
    build:
      dockerfile: devcontainer.dockerfile
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock